In [9]:
import cv2
import numpy as np
import random
def Fitness_Function(img, thresholds):
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    pixels = cv2.calcHist([img_gray], [0], None, [256], [0, 256])
    p = pixels / (img_gray.shape[0] * img_gray.shape[1])
    x = np.linspace(1, 256, 256)

    total_variance = 0
    for i in range(len(thresholds) + 1):
        if i == 0:
            a = np.sum(p[0:thresholds[i]])
            m = np.dot(x[0:thresholds[i]], p[0:thresholds[i]]) / a if a != 0 else 0
            variance = np.sum(p[0:thresholds[i]] * (x[0:thresholds[i]] - m) ** 2)
        elif i == len(thresholds):
            a = np.sum(p[thresholds[i-1]:256])
            m = np.dot(x[thresholds[i-1]:256], p[thresholds[i-1]:256]) / a if a != 0 else 0
            variance = np.sum(p[thresholds[i-1]:256] * (x[thresholds[i-1]:256] - m) ** 2)
        else:
            a = np.sum(p[thresholds[i-1]:thresholds[i]])
            m = np.dot(x[thresholds[i-1]:thresholds[i]], p[thresholds[i-1]:thresholds[i]]) / a if a != 0 else 0
            variance = np.sum(p[thresholds[i-1]:thresholds[i]] * (x[thresholds[i-1]:thresholds[i]] - m) ** 2)

        total_variance += variance

    # 计算 sigma_in
    sigma_in = 0
    for i in range(len(thresholds) + 1):
        if i == 0:
            a = np.sum(p[0:thresholds[i]])
            m = np.dot(x[0:thresholds[i]], p[0:thresholds[i]]) / a if a != 0 else 0
            sigma_in += np.sum(p[0:thresholds[i]] * (x[0:thresholds[i]] - m) ** 2)
        elif i == len(thresholds):
            a = np.sum(p[thresholds[i-1]:256])
            m = np.dot(x[thresholds[i-1]:256], p[thresholds[i-1]:256]) / a if a != 0 else 0
            sigma_in += np.sum(p[thresholds[i-1]:256] * (x[thresholds[i-1]:256] - m) ** 2)
        else:
            a = np.sum(p[thresholds[i-1]:thresholds[i]])
            m = np.dot(x[thresholds[i-1]:thresholds[i]], p[thresholds[i-1]:thresholds[i]]) / a if a != 0 else 0
            sigma_in += np.sum(p[thresholds[i-1]:thresholds[i]] * (x[thresholds[i-1]:thresholds[i]] - m) ** 2)

    vars = float(total_variance/sigma_in)
    print("vars="+str(vars))
    return vars

img = cv2.imread("Images/mopi.jpeg")
num_thresholds = 2  # 设置阈值的数量
#def OTSU_Multi_IMPROVE_ACO(img, num_thresholds):
num_ants = 10
max_iter = 20
alpha = 1.0
beta = 2.1
rho = 0.3
Q = 1.3
pheromone = np.ones(256)
best_thresholds = [0] * (num_thresholds)
best_maxvar = 0
threshold_prob = np.ones(256) / 256

for iteration in range(max_iter):
    ants = np.random.choice(np.arange(0, 256), size=(num_ants, num_thresholds), p=threshold_prob,replace=False)
    ants = np.sort(ants, axis=1)
    print(ants)
    for ant in ants:
        maxvar = Fitness_Function(img, np.sort(ant))
        print("maxvar="+str(maxvar))
        if maxvar > best_maxvar:
            best_maxvar = maxvar
            best_thresholds = np.sort(ant)
            print("Result="+str([best_maxvar,best_thresholds]))

    # 更新信息素
    for i in range(num_ants):
        th = ants[i]
        maxvar = Fitness_Function(img,np.sort(ant))
        pheromone[th-1] += Q * maxvar                          # 为每一只蚂蚁走过路径的信息素加权

    pheromone *= (1 - rho)


    pheromone_max = np.max(pheromone)
    threshold_prob = pheromone / pheromone_max
    threshold_prob /= np.sum(threshold_prob)  # 确保概率和为1

    #print(f"Iteration {iteration+1}: Best Thresholds {best_thresholds}, Best Maxvar {best_maxvar}")


    #return best_thresholds, best_maxvar
#print("best_maxvar"+str(best_maxvar))
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
dst = gray.copy()
th1 = best_thresholds[0]
th2 = best_thresholds[1]
for row in range(0,gray.shape[0]):
    for col in range(0,gray.shape[1]):
        if dst[row, col]<th1:
            dst[row, col]=0
        elif dst[row, col]>=th1 and dst[row, col]<=th2:
            dst[row, col] =127
        else:
            dst[row, col] = 255
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
#print(OTSU_Multi_IMPROVE_ACO(img, num_thresholds))



[[ 95 142]
 [ 63 231]
 [ 33 188]
 [ 46 101]
 [ 15 232]
 [  8  32]
 [202 225]
 [116 167]
 [ 25  79]
 [127 131]]
vars=1.0
maxvar=1.0
Result=[1.0, array([ 95, 142])]
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
[[153 157]
 [232 248]
 [224 230]
 [ 26 210]
 [ 70 207]
 [ 24 192]
 [ 25 218]
 [ 66 198]
 [ 38  55]
 [ 50 107]]
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
vars=1.0
[[153 218]
 [  9 190]
 [ 88 230]
 [ 19 240]
 [ 53 179]
 [ 71 184]
 [163 213]
 [ 37 231]
 [ 45 245]
 [113 206]]
vars=1.0
maxvar=1.0
vars=1.0
maxvar=1.0
vars=1.0
maxvar